# Generated by Django 2.0 on 2018-07-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houses_in_stage_i', models.PositiveIntegerField(default=0)),
                ('houses_in_stage_ii', models.PositiveIntegerField(default=0)),
                ('houses_in_stage_iii', models.PositiveIntegerField(default=0)),
                ('received_tranche_i', models.PositiveIntegerField(default=0)),
                ('received_tranche_ii', models.PositiveIntegerField(default=0)),
                ('received_tranche_iii', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gaunpalika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_municipality', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaunpalika', to='visualizations.District')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='gaunpalika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='visualizations.Gaunpalika'),
        ),
    ]
