# Generated by Django 2.0 on 2018-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0002_auto_20180702_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='source_is_fieldSight',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='data',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
