# Generated by Django 2.0 on 2018-07-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0004_auto_20180710_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='number_of_women',
        ),
    ]
