# Generated by Django 2.0 on 2018-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0005_remove_data_number_of_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='women_percentange',
            field=models.IntegerField(default=0),
        ),
    ]
