# Generated by Django 2.0 on 2018-07-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0006_data_women_percentange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='women_percentange',
        ),
    ]
