# Generated by Django 2.0.7 on 2018-07-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0010_recentstories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentstories',
            name='banner',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentstories',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
