# Generated by Django 2.0 on 2018-07-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0011_auto_20180724_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentstories',
            name='content',
        ),
    ]
