# Generated by Django 2.0 on 2018-07-24 06:48

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0012_remove_recentstories_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentstories',
            name='content',
            field=froala_editor.fields.FroalaField(default=''),
            preserve_default=False,
        ),
    ]
