# Generated by Django 2.0 on 2018-07-25 10:40

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0013_recentstories_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentstories',
            name='banner',
            field=stdimage.models.StdImageField(upload_to='', validators=[stdimage.validators.MinSizeValidator(1600, 600)]),
        ),
        migrations.AlterField(
            model_name='recentstories',
            name='thumbnail',
            field=stdimage.models.StdImageField(upload_to='', validators=[stdimage.validators.MinSizeValidator(100, 100)]),
        ),
    ]
