# Generated by Django 2.0 on 2018-07-26 05:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0014_auto_20180725_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentstories',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
