# Generated by Django 2.0 on 2018-07-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0015_auto_20180726_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentstories',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='recentstories',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
