# Generated by Django 2.0 on 2018-08-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0018_auto_20180812_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='gaunpalika',
            options={'verbose_name_plural': 'Gaunpalika'},
        ),
        migrations.AlterModelOptions(
            name='housingcompletion',
            options={'verbose_name_plural': 'Housing Completion'},
        ),
        migrations.AlterModelOptions(
            name='recentstories',
            options={'verbose_name_plural': 'Recent Stories'},
        ),
        migrations.AlterModelOptions(
            name='reconstructiongrant',
            options={'verbose_name_plural': 'Reconstruction Grant'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name_plural': 'Training'},
        ),
    ]
