# Generated by Django 2.0 on 2018-08-13 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0020_event_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensedAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='recentstories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 6, 20, 9, 712100, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='recentstories',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
