# Generated by Django 2.0 on 2018-08-13 06:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0021_auto_20180813_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStakeholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='project_stakeholders/')),
            ],
        ),
        migrations.AlterField(
            model_name='recentstories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 6, 22, 19, 867503, tzinfo=utc)),
        ),
    ]
