# Generated by Django 2.0 on 2018-08-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0023_auto_20180813_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentstories',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
