# Generated by Django 2.0 on 2018-08-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0024_auto_20180813_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentstories',
            name='use_banner',
            field=models.BooleanField(default=False),
        ),
    ]
