# Generated by Django 2.0 on 2018-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0025_recentstories_use_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('IMAGE', 'Image')], default='AUDIO', max_length=300),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
