# Generated by Django 2.0 on 2018-08-13 16:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0026_auto_20180813_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
