# Generated by Django 2.0 on 2018-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0028_auto_20180814_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
    ]
