# Generated by Django 2.0 on 2018-08-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0030_auto_20180815_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='partner_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.ProjectStakeholders'),
        ),
    ]
