# Generated by Django 2.0 on 2018-08-19 11:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0032_auto_20180819_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstakeholders',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='partner_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_stakeholders', to='visualizations.ProjectStakeholders'),
        ),
    ]
