# Generated by Django 2.0 on 2018-08-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0033_auto_20180819_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstakeholders',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
