# Generated by Django 2.0 on 2018-08-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0034_projectstakeholders_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
