# Generated by Django 2.0 on 2018-08-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0035_contact_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentStory',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'Project Overview'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Reconstruction per Municipality'},
        ),
        migrations.AlterModelOptions(
            name='dispensedamount',
            options={'verbose_name_plural': 'Disbursed Amount'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='housingcompletion',
            options={'verbose_name_plural': 'Reconstruction Stages'},
        ),
        migrations.AlterModelOptions(
            name='projectstakeholders',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='recentstories',
            options={'verbose_name_plural': 'Stories From The Field'},
        ),
        migrations.AlterModelOptions(
            name='totalamount',
            options={'verbose_name_plural': 'Total EOI Funding'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterField(
            model_name='recentstories',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Short Title'),
        ),
    ]
