# Generated by Django 2.0 on 2018-08-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0036_auto_20180830_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentstories',
            name='description',
            field=models.CharField(max_length=255, verbose_name='subtitle'),
        ),
    ]
