# Generated by Django 2.0 on 2018-10-11 06:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0037_auto_20180831_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='STFCLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('contact_person', models.CharField(max_length=200)),
            ],
        ),
    ]
