# Generated by Django 2.0 on 2018-10-11 06:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0038_stfclocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stfclocations',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stfclocations',
            name='longitude',
        ),
        migrations.AddField(
            model_name='stfclocations',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
