# Generated by Django 2.0 on 2018-10-11 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0039_auto_20181011_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stfclocations',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stfc_locations', to='visualizations.District'),
        ),
    ]
