# Generated by Django 2.0 on 2018-10-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0040_auto_20181011_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='stfclocations',
            name='district_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
