# Generated by Django 2.0 on 2018-10-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0041_stfclocations_district_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stfclocations',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stfc_locations', to='visualizations.District'),
        ),
    ]
