# Generated by Django 2.0 on 2018-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0042_auto_20181011_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stfclocations',
            name='district',
        ),
        migrations.AlterField(
            model_name='stfclocations',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stfclocations',
            name='contact_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stfclocations',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stfclocations',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
