# Generated by Django 2.0 on 2018-10-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0044_auto_20181012_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercontact',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='contacts-logo/'),
        ),
    ]
