# Generated by Django 2.0 on 2018-10-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0045_othercontact_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
