# Generated by Django 2.0 on 2018-10-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0046_contact_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
