# Generated by Django 2.0 on 2018-10-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0047_auto_20181012_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstakeholders',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('PARTNER', 'Partner')], default='PARTNER', max_length=50),
        ),
    ]
