# Generated by Django 2.0 on 2018-11-15 07:05

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0049_auto_20181115_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentstories',
            name='banner',
            field=stdimage.models.StdImageField(upload_to='', validators=[stdimage.validators.MaxSizeValidator(1600, 200)]),
        ),
    ]
