# Generated by Django 2.0 on 2018-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0052_recentstories_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentstories',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_image/'),
        ),
    ]
